import datetime
from datetime import datetime as Datetime
from sys import argv

print(datetime.date(year=2014,month=1,day=6))
print(datetime.date.today())
print(datetime.date.fromtimestamp(1000000000))
print(datetime.date.fromordinal(720669))
d=datetime.date.today()
print(d.year,'-',d.month,'-',d.day)
print(d.weekday())
print(d.isoweekday())
print(d.isoformat())
print(d.strftime('%A  %d %B - %Y'))
print("The date is {:%A %d %B %Y}".format(d))
#As above solution is platform dependent so better is to extract date component
print('{date:%A} {date.day} {date:%B} {date.year}'.format(date=d)) # pythonic way
print('min={min},max={max},resolution={resolution}'.format(min=datetime.date.min,max=datetime.date.max,resolution=datetime.date.resolution))
print(datetime.time(3,12,2,200))
print(datetime.time(hour=23, minute=59, second=59, microsecond=999999))
t=datetime.time(10, 32, 47, 675623)
print(t.hour,t.minute,t.second,t.microsecond)
print(t.isoformat())
print(t.strftime('%Hh%Mm%Ss'))
print("{t.hour}h{t.minute}m{t.second}s".format(t=t))
print('min={min},max={max},resolution={resolution}'.format(min=datetime.time.min,max=datetime.time.max,resolution=datetime.time.resolution))
print(Datetime(2003,5,12,14,33,22,245323))
print(Datetime.now(),Datetime.today())
print(Datetime.utcnow())
print(Datetime.fromordinal(5))
print(datetime.datetime.fromtimestamp(3635352))
print(datetime.datetime.utcfromtimestamp(3635352))
print(Datetime.combine(d,t))
dt=datetime.datetime.strptime("Monday 6 January 2014, 12:13:31", "%A %d %B %Y, %H:%M:%S")
print(dt)
print(dt.date())
print(dt.time())
print(dt.timetz())
print(dt.isoformat())
print(datetime.timedelta(milliseconds=1,microseconds=1000))
td = datetime.timedelta(weeks=1, minutes=2, milliseconds=5500)
print(td,td.days,td.seconds,td.microseconds)
print(str(td))
print(repr(td))
a = datetime.datetime(year=2014, month=5, day=8, hour=14, minute=22)
b = datetime.datetime(year=2014, month=3, day=14, hour=12, minute=9)

print(a-b)
print((a-b).total_seconds())
print(datetime.date.today() + datetime.timedelta(weeks=1) * 3)
f = datetime.time(14, 30, 0)
g = datetime.time(15, 45, 0)
# print(f-g)
cet = datetime.timezone(datetime.timedelta(hours=1), "CET")
print(cet)
departure = datetime.datetime(year=2014, month=1, day=7, hour=11, minute=30, tzinfo=cet)
arrival=datetime.datetime(year=2014,month=1,day=7,hour=13,minute=5,tzinfo=datetime.timezone.utc)
print(arrival-departure)
